package day_32;

public class ExceptionDemo11 {
    public static void main(String[] args) {
//        int[] arr = {1, 2, 3, 4, 5};
//        try {
//            System.out.println(arr[10]);
//        } catch (ArrayIndexOutOfBoundsException e) {
////            String message = e.getMessage();
////            System.out.println(message);
//
////            String string = e.toString();
////            System.out.println(string);
//
//            e.printStackTrace();
//        }
//        System.out.println("看看我执行了吗");

        System.err.println(123);
    }
}
